version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
  db:
    container_name: Db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
        - ./.containers/db:/var/lib/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "password123"
