version: '3.4'

services:
  cleanproject-db:
    image: postgres:16.2
    container_name: CleanProject.Db
    volumes:
      - ./.containers/cleanproject-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cleanproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cleanproject-pgadmin:
    image: dpage/pgadmin4
    container_name: CleanProject.PgAdmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: cleanproject@gmail.com
      PGADMIN_DEFAULT_PASSWORD: cleanproject 
    volumes:
      - ./.containers/cleanproject-pgadmin:/var/lib/pgadmin/data
